### PR TITLE
#16 Z-Scale Implementation

### PR DESCRIPTION
**Pull request by gusmalikah**
#16 Z-Scale Implementation along with few improvements in the Y-Scale.
The CSS is changed from absolute values to flexbox for better responsiveness. A tick is also added with the values and the values on Z scale also has percentage sign now.

### CODE REVIEW

**Review by MajaLinder — CHANGES_REQUESTED** [review]
It's good that you fixed the bug, I ran the code and it's working, however this bug was connected to another open PR so make sure that PR is changed to only update the README. 

There was a discussion about what to call the third axis. A z axis is three dimensional so we should have another name. Tibco calls it "color axis" and this name is also specified in the acceptance criteria.

Otherwise good work!

**Comment by MajaLinder** [comment]
Also, I found on line 24 in index.js that you have _mod.property("split-bars")_ , should this not be stackbars?

**Comment by MalikWaleed3** [comment]
@MajaLinder I have done changes according to your previous comments, kindly go through them once again.

**Review by MajaLinder — APPROVED** [review]
Looks good!

**Pull request merged**
