### PR TITLE
Refactoring

### LINKED ISSUE #86: Refactoring repository
Based on Tibco Input and team discussion over technical design, will refactor code to start over from the tibco example code.

### PR DESCRIPTION
**Pull request by b4rdha**
Fixes  #86 Refactoring and #84 Data transformation layer

Refactored the code to change the way data was handled and modelled middle layer.

### CODE REVIEW

**Review by MajaLinder — COMMENTED** [review]
I'm a little confused by the folder structure. It looks like a lot of our files are in a folder called node_modules, but when I pull the code it doesn't look the same.

**Comment by MajaLinder** [comment]
Picture is from index.ts. I think hierarchyAxisName should be categoryAxisName (and changed everywhere it applies in the code)
image

**Comment by MajaLinder** [comment]
What are these properties for? 
image

**Comment by AstridBer** [comment]
Nice Work! But I'm not sure I understand the structure.  I don't really get what stackedBar is. Why does it consist of multiple bars? Does it have anything to do with color axis?

**Comment by b4rdha** [comment]
> What are these properties for? image

These are default values for the requirements here: 
Screenshot 2022-11-07 at 14 04 08

We should think further if we want to add the 80/20 cutoff as well.

**Comment by b4rdha** [comment]
> Nice Work! But I'm not sure I understand the structure. I don't really get what stackedBar is. Why does it consist of multiple bars? Does it have anything to do with color axis? ParetoStruct

It covers the case where we have multiple contributors to a category, like here: 
Screenshot 2022-11-07 at 14 07 08
That's why it's composed of bars.

**Comment by MajaLinder** [comment]
> 

Aren't these future features to implement later then?

**Comment by b4rdha** [comment]
> > 
> 
> Aren't showCumulativeFrequencyLine and showLineMarkers future features to implement later then?

We don't have to implement it now, I guess we can just use the stacked bar to draw the main bar. But the model doesn't do any harm to stay there. You don't use it now, but it makes the future implementations easier, instead of having to refactor it again after we draw them one way now.

**Comment by MajaLinder** [comment]
I don't really understand this part, what are minValue, maxValue and grandTotal for? Shouldn't we have the cumulative line here as well?
image

**Comment by AstridBer** [comment]
> It covers the case where we have multiple contributors to a category, like here: Screenshot 2022-11-07 at 14 07 08 
That's why it's composed of bars.

So in this example StackedBar.lables would be MW, NE, SE etc. And bar.label would be Grocery etc? 

I remember that we had a discussion about the colorHierarchy before and that we weren't sure if we needed to use it for a pareto chart. Maybe it is a good idea to double check with stakeholders if they want that functionality? Does anyone else remember if we decided anything about it?

**Comment by b4rdha** [comment]
> > 
> 
> Aren't showCumulativeFrequencyLine and showLineMarkers future features to implement later then?

Ah them, well I just have the placeholders for default values. For the future we can address the requirements as we see fit.  

> I don't really understand this part, what are minValue, maxValue and grandTotal for? Shouldn't we have the cumulative line here as well? image

yes, I think so, but I didn't implement anything related to cumulative line here. Just structured the data, so now every StackedBar has the corresponding cumulativeValue, so sum of values up to and including this stacked bar's value. They can be used to plot the line in the next task.

**Comment by b4rdha** [comment]
> > It covers the case where we have multiple contributors to a category, like here: Screenshot 2022-11-07 at 14 07 08
> > That's why it's composed of bars.
> 
> So in this example StackedBar.lables would be MW, NE, SE etc. And bar.label would be Grocery etc?
> 
> I remember that we had a discussion about the colorHierarchy before and that we weren't sure if we needed to use it for a pareto chart. Maybe it is a good idea to double check with stakeholders if they want that functionality? Does anyone else remember if we decided anything about it?

I

> nce in new issue
> Edit
> Hide
> Delete

Sorry, I missed this earlier. Yes, precisely, I thought StackedBar.label = Category, and Bar.Label = Sub-category

**Review by MajaLinder — CHANGES_REQUESTED** [review]
In index.html and main.css there are things probably taken from an example code that we will not have, so we should remove that.

**Comment by b4rdha** [comment]
> In index.html and main.css there are things probably taken from an example code that we will not have, so we should remove that.

Yes, I didn't touch that part, I think we should do that when we add the styling component.

**Comment by MajaLinder** [comment]
> > In index.html and main.css there are things probably taken from an example code that we will not have, so we should remove that.
> 
> Yes, I didn't touch that part, I think we should do that when we add the styling component.

I think it's better to not have clutter from an example that we won't use. I don't mean that you should add what we need, just to remove some things.

**Review by AstridBer — APPROVED** [review]

**Pull request merged**
