### PR TITLE
#43 Origin adjusting

### LINKED ISSUE #43: Adjust axis origin
The current display shows that the axis origin is above the positive values for bars. Needs to be adjusted to start in the same level as the x axis as the origin O(0,0) 

Acceptance criteria: When the data is visualized, the origin of the axis is the initial value that corresponds to the O point in the x,y axis 0(0, 0). 

Planning poker score: 13 (0-89 Fibonacci)

### PR DESCRIPTION
**Pull request by b4rdha**
Fixes #43 adding margins to the bottom to start in origin

### CODE REVIEW

**Comment by MajaLinder** [comment]
My first thought is if the upper mark should be adjusted as well. I see in Tibcos prototype they're not, but one bar is also exceeding 100% there, should that be possible? In the bar chart example code the upper mark is almost at the top of the y-axis though.
Also, at first glance it feels like changing to -6px is a hardcoded fix, but I'm not sure.

**Comment by b4rdha** [comment]
I agree it's a little bit hardcoded, I went with the solution we had there, as I don't feel confident/skilled enough to change the entire styling. We can decide in the team. 

The difference I added is not causing the issue with the marking, as I noticed it's there on the MVP also 
Before: 
Screenshot 2022-10-12 at 11 25 33

After: 


So I suppose we can make a new issue for that?

**Comment by MajaLinder** [comment]
Yeah, we might have to treat the entire styling as one issue later.
So we should have a new issue for the upper mark being adjusted at the top of the axis? You can also see the first bar reaching a little higher than to the upper mark.

**Comment by MajaLinder** [comment]
Nice Bardha! Not sure if you intend to add more commits, but here are a few comments:

- After merging with main the percentage scale doesn't look the way it did
- The bars are overlapping the y-axis
- The ticks appearance have changed
- The upper mark is perhaps slightly too high

image

image

**Comment by b4rdha** [comment]
The issue is obsolete in the new code refactor and handled in D3 instead.

**Pull request closed without merging**
